name: Secret Scan

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: Detect Secret Leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | \
          sh -s -- -b /usr/local/bin

      - name: Scan PR changes for leaked secrets
        run: |
          git diff --unified=0 origin/${{ github.base_ref }}...HEAD > pr.diff
          gitleaks stdin --verbose --redact < pr.diff

#      - name: Run Gitleaks
#        uses: gitleaks/gitleaks-action@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



