name: Secret Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: Detect Secret Leaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PR diff
        run: |
          git diff --unified=0 origin/${{ github.base_ref }}...HEAD > pr.diff

      - name: Scan PR changes for leaked secrets
        run: |
          docker run --rm -i \
            ghcr.io/gitleaks/gitleaks:latest \
            stdin --verbose --redact < pr.diff



